### ISSUE TITLE
win10 Hotkey conflict

### ISSUE THREAD

**Issue by anjia0532** [lambdalab/UserFeedbacks#3]
os version win10 1703

<kbd>win</kbd>+<kbd>shift</kbd>+<kbd>s</kbd> is screenshot  hotkey

**Comment by mw-ding** [comment]
0.6.2 now support shortcut customization now.

**Comment by anjia0532** [comment]
@mw-ding thanks for your reply.but in the chrome app store,the insightio-for-github latest version is 0.6.1 

https://chrome.google.com/webstore/detail/insightio-for-github/pmhfgjjhhomfplgmbalncpcohgeijonh?utm_source=chrome-app-launcher-info-dialog

**Comment by anjia0532** [comment]
how to upgrade to v0.6.2 ? just wait?

**Comment by mw-ding** [comment]
yes, we just upload the release. should be available in about 1 hour. You chrome will upgrade your plugin automatically.

**Comment by anjia0532** [comment]
0.6.2 is very cool.thanks for your job.
