### ISSUE TITLE
GitHub API limit will be reached if requests are from single IP

### ISSUE THREAD

**Issue by chongzhe** [lambdalab/UserFeedbacks#4]
![image](https://user-images.githubusercontent.com/2304183/28804752-0b370fd0-761a-11e7-9c84-045c2a2e44f1.png)
![image](https://user-images.githubusercontent.com/2304183/28804756-0ed9b426-761a-11e7-9496-61e9ad3c5ce5.png)

**Comment by mw-ding** [comment]
Since 0.6.2, we can now provide github personal access token to fix this issue.
