### ISSUE TITLE
Cannot log in with github due to abnormal logging in procedure 

### ISSUE THREAD

**Issue by the0demiurge** [lambdalab/UserFeedbacks#7]
After I clicked "Log in with GitHub" and accepted the OAuth, to review what permissions it requests, I clicked "back button" on the browser, and there shows "Log in with GitHub" forever\
![image](https://user-images.githubusercontent.com/11363529/35077349-c8b260fc-fc37-11e7-9172-d91595d992b4.png)
 
I've tried any methods except factory-reset my chrome browser, including re-install this extension or re-auth the insight.io, but it's not working :(

Please fix it, thx:)

from google-chrome on Ubuntu 16.04 LTS

**Comment by mw-ding** [comment]
@the0demiurge hey, can you help to open the chrome web console to see if there is any exception in there?

![image](https://user-images.githubusercontent.com/987855/35077505-b8b6cf66-fc38-11e7-86f4-f620131c2857.png)

![image](https://user-images.githubusercontent.com/987855/35077509-c5008cd0-fc38-11e7-9989-435ed5000c50.png)

**Comment by the0demiurge** [comment]
![image](https://user-images.githubusercontent.com/11363529/35077578-1addc58c-fc39-11e7-8ff4-e848c05c4cc1.png)
[github.com-1516242004432.log](https://github.com/lambdalab/UserFeedbacks/files/1641361/github.com-1516242004432.log)

**Comment by mw-ding** [comment]
@the0demiurge  Thanks. Can you do me another favor? visit https://insight.io and see if you have already logged in or not? I highly suspect that you are not logged in yet. If so, we can start to see what is the issue.

**Comment by the0demiurge** [comment]
Unfortunately, I've checked that I'm logged in
![image](https://user-images.githubusercontent.com/11363529/35077920-83a5a0de-fc3a-11e7-9a5a-9f3a3b505396.png)
and https://insight.io/api/user/profile?hostType=0 in browser returns 
![image](https://user-images.githubusercontent.com/11363529/35077944-a7d2b7d0-fc3a-11e7-8925-4145b7b06678.png)
However, this extension still shows not logged in :(

**Comment by mw-ding** [comment]
@the0demiurge hmm... hold on, let me see what's going on here.

**Comment by mw-ding** [comment]
@the0demiurge can you provide more details of your browser/os? the version of Chrome, OS? I am trying to reproduce the issue

**Comment by the0demiurge** [comment]
Thank you :)

**Comment by the0demiurge** [comment]
![image](https://user-images.githubusercontent.com/11363529/35078101-8b6f2406-fc3b-11e7-9e78-6333609b8c12.png)
![image](https://user-images.githubusercontent.com/11363529/35078111-98e306ac-fc3b-11e7-869f-33ad7c83368e.png)

**Comment by the0demiurge** [comment]
This problem isn't solved in spite of disabling all the extensions

**Comment by mw-ding** [comment]
We are trying to replicate your working env now. In the meantime, do you mind taking a deep dive into the `/profile` request as below:

![image](https://user-images.githubusercontent.com/987855/35078650-2bf1076c-fc3e-11e7-8f9c-57fc9190ce59.png)

screenshot the details would be appreciated.

**Comment by the0demiurge** [comment]
![image](https://user-images.githubusercontent.com/11363529/35078803-f871b0de-fc3e-11e7-967d-f6d6312cd81d.png)
No cookie found

**Comment by mw-ding** [comment]
@the0demiurge Yea, this makes sense. 

we are still working on reproduce this issue. will get you right back when we find anything.

**Comment by the0demiurge** [comment]
thank you：）

**Comment by mw-ding** [comment]
@the0demiurge Hey, it's highly possible that you have opt in the following content setting item in Chrome:

![image](https://user-images.githubusercontent.com/987855/35256543-5118d12e-002f-11e8-8c03-12254ade84d7.png)


Can you help to double check? Follow [this answer](https://stackoverflow.com/a/24176601/4460470) to find this particular setting item

PS: we have recreated the same env as yours, cannot reproduce the issue by default though.

![image](https://user-images.githubusercontent.com/987855/35256599-8679ee20-002f-11e8-882d-553fe620fb00.png)

**Comment by the0demiurge** [comment]
That worked!
It is the blocking of third-party cookie that contributes this issue

**Comment by afedulov** [comment]
Please provide domains that need to be added to the exceptions. Simply not blocking third party cookies for all sites is not a good solution.

**Comment by mw-ding** [comment]
@afedulov Thanks for the feedback Alex. Yes, this is a better option.

![image](https://user-images.githubusercontent.com/987855/40892442-0a94c88c-674c-11e8-89a0-4cb63ea52781.png)
