### ISSUE TITLE
Conflicts with Github's hotkey 'S'

### ISSUE THREAD

**Issue by Sky-Walkrr** [lambdalab/UserFeedbacks#8]
In https://github.com page, we usually use key `S` to focus on search bar to search repos and everything on Github, but Insight Chrome plugin hijacks it and replaces with insight's code-search. This seems annoying and inefficient.
Please don't hijack hotkey S in Github homepage.

**Comment by mw-ding** [comment]
@Sky-Walkrr Thanks for reporting back. Will fix this issue in the next release.

**Comment by mw-ding** [comment]
@Sky-Walkrr hey, this issue should be fixed by the latest release. can you double check?

**Comment by Sky-Walkrr** [comment]
Fixed.Thanks for your job.
