### ISSUE TITLE
Mac chrome cannot login

### ISSUE THREAD

**Issue by Sutonline** [lambdalab/UserFeedbacks#9]
Hi,
When use window's chrome explorer, it works. But when i switch to mac chrome explorer, login `https://github.com/login/oauth/authorize?scope=xxxx` redirect to original page. Insight.io extension says not logged. So this is a bug or need some settings?

**Comment by mw-ding** [comment]
@Sutonline Thanks for reporting back the issue. The team is working on this. Will get back to you soon

**Comment by mw-ding** [comment]
@Sutonline Hey, I think it's highly likely that your issue is similar to [this one](https://github.com/lambdalab/UserFeedbacks/issues/7#issuecomment-359663567). Can you try to double check if the `block third-party cookies` has been enabled in your chrome?

**Comment by Sutonline** [comment]
Thank you, your suggestion is helpful. My chrome not block third-party cookies, but I installed an extendsion named Ghostery which will block trackers. It's werid that i allow all github.com trackers (google and mixpanel) but the problem not solved. When I disabled Ghostery for github.com, it works. Maybe this plugin have some "trackers" which not recognized by Ghostery.
